DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS roles;

CREATE TABLE users 
(
	id BIGINT NOT NULL PRIMARY KEY,
	username VARCHAR(100) NOT NULL,
	password VARCHAR(100) NOT NULL,
	enabled BOOLEAN NOT NULL
);

CREATE TABLE roles
(
	user_id BIGINT REFERENCES users(id),
	role VARCHAR(100) NOT NULL,
	id BIGINT NOT NULL PRIMARY KEY
);