server:
  port: 5555

spring:
  zipkin:
    baseUrl: http://localhost:9222
    
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/
        
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.visdan: DEBUG
